site_name: Kubernetes Adoption Journey
site_url:
  !ENV [SITE_URL, "https://digitalocean.github.io/k8s-adoption-journey/"]
site_description: Hands-on tutorial for going from day-1 to production on DigitalOcean Kubernetes.
copyright: DigitalOcean
repo_url: "https://github.com/digitalocean/k8s-adoption-journey"
docs_dir: !ENV [DOCS_DIR, "docs"]
site_dir: !ENV [SITE_DIR, "site"]

nav:
  - Intro: index.md
  - Getting started:
      - Installing required tools: 01-getting-started/installing-required-tools.md
      - Authenticating with the DigitalOcean API: 01-getting-started/do-api-auth.md
      - Set up a Digital Ocean container registry: 01-getting-started/setup-docr.md
      - Preparing the demo application: 
        - Repository setup: 01-getting-started/building-and-pushing-docker-images/introduction-and-repository-setup.md
        - Building and pushing images with Docker: 01-getting-started/building-and-pushing-docker-images/building-and-pushing-images-using-docker.md
        - Building and pushing images with Cloud Native Buildpacks: 01-getting-started/building-and-pushing-docker-images/building-and-pushing-images-using-cnb.md
  - Development environment:
      - Set up Development DOKS: 02-development/setup-doks-dev.md
      - Tilt for local development: 02-development/tilt-local.md
      - Tilt for remote development: 02-development/tilt-remote.md
      - Set up ingress: 02-development/setup-ingress-dev.md
      - Observability: 02-development/observability-dev.md
  - Staging environment:
      - Set up Staging DOKS: 03-staging/setup-doks-staging.md
      - Deploying the online boutique sample application: 03-staging/deploying-the-online-boutique-sample-application-staging.md
      - Set up ingress: 03-staging/setup-ingress-staging.md
      - Observability: 03-staging/observability-staging.md
  - Production environment:
      - Set up Production DOKS: 04-production/setup-doks-production.md
      - Deploying the online boutique sample application: 04-production/deploying-the-online-boutique-sample-application-production.md
      - Set up ingress: 04-production/setup-ingress-production.md
      - Observability: 04-production/observability-production.md
  - Continuous integration and deployments:
      - Set up continuous integration: 05-ci-cd/setup-continuous-integration.md
      - Set up continuous deployments: 05-ci-cd/setup-continuous-deployments.md
  - Promote releases:
      - Set up release process: 06-promote-releases/setup-release-process.md
      - Promote releases to upper environments: 06-promote-releases/promote-releases-to-upper-envs.md

theme:
  name: material
  logo: assets/do_logo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  # simplifies relative linking between documents
  # https://github.com/midnightprioriem/mkdocs-autolinks-plugin
  - autolinks
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
